version: '3.8'

services:
  # Spring test also runs checkstyle
  spring-test:
    build:
      context: ./spring
      dockerfile: Dockerfile.test
    volumes:
      - ./spring-test-results:/workspace/app/target/site/jacoco
  python-test:
    build: ./scraper
    command: poetry run pytest --cov scraper
    environment:
      - DB_ADDRESS=localhost
      - DB_DATABASE=testdb
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_PORT=3306

  python-lint:
    build: ./scraper
    command: poetry run flake8